project:
  type: book
  output-dir: _book

lang: is

book:
  title: "Saga Golfklúbbsins á Flúðum"
  subtitle: "Frá upphafi til dagsins í dag"
  author: "Árni Tómasson"
  date: today
  date-format: "D. MMMM YYYY"
  repo-url: https://github.com/tungufoss/fludir-golf
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - kaflar/01-upphafid.qmd
    - kaflar/02-vollurinn.qmd
    - kaflar/03-motin.qmd
    - kaflar/04-felagarnir.qmd
    - kaflar/05-kaup-a-selsvelli.qmd
    - kaflar/06-rekstur.qmd
    - kaflar/07-timalina.qmd

format:
  html:
    theme: cosmo
    toc-title: "Efnisyfirlit"
