---
pagetitle: "Saga Selsvallar | Kaup á Selsvelli"
---

# Kaup á Selsvelli

## Upphaf

Í september 2021 tilkynntu vallareigendur þau Halldóra Halldórsdóttir og Unnsteinn Eggertsson f.h. vallareigenda, að þau hygðust hætta rekstri golfvallar og veitingasölu og auglýsa völlinn til sölu. Þau tóku við rekstrinum árið 2018 af foreldrum Halldóru, þeim Halldóri Guðnasyni og Ástríði Daníelsdóttur sem stofnuðu völlinn 1985 og eru heiðursfélagar í GF. Halldór Guðnason stofnandi Selsvallar og GF, sem látið hafði af störfum sem vallarstjóri 2018, hljóp aftur í skarðið sumarið 2021. Um haustið 2021 greindist Halldór með illkynja krabbamein og lést hann í janúar 2022. Verður hans ávallt minnst fyrir frumkvæði sitt og dugnað við uppbyggingu Selsvallar.

## Fyrstu skref

Félagar í GF voru í mikilli óvissu um hver yrði framtíð vallarins, því við fyrstu sýn virtist ókleift fyrir klúbbinn að ráða við að kaupa völlinn og tengdar eignir. Þegar fréttist af því að hjóhýsaeigendur hefðu sýnt áhuga á að kaupa völlinn og breyta æfingasvæðinu til að byrja með í svæði fyrir hjólhýsi, ýtti það við formanni GF að ræða við félagsmenn og leggjast í útreikninga á því hvað mögulega væri unnt að gera. Byggt á fyrirliggjandi upplýsingum, bráðabirgða útreikningum og bjartsýnum forsendum um þátttöku félagsmanna í fjármögnun, fór formaður á fund vallareigenda og ræddi um hugsanleg kaup GF á vellinum.

## Samkomulag um forkaupsrétt til ársloka 2021

Vallareigendur tóku málaleitan GF vel og var snemma ljóst að þau vildu helst að GF eða aðilar á vegum GF keyptu völlinn og allar tengdar eignir, en þannig yrði best tryggt að Selsvöllur yrði áfram starfræktur á sama stað og það mikla frumkvæði og uppbyggingarstarf sem unnið hefði verið frá stofnun vallarins, fengi að lifa og þróast áfram.

Eftir nokkra fundi þar sem mismunandi sjónarmið voru reifuð, taldi formaður GF kominn grunn að samkomulagi sem gæti gengið upp miðað við bjartsýnar forsendur og fékk samþykki stjórnar GF til að ganga til samninga við vallareigendur. Þann 6. október 2021 hittust Árni Tómasson formaður GF og þau Halldóra Halldórsdóttir og Unnsteinn Eggertsson eigendur Selsvallar, en þau fóru jafnframt með umboð fyrir Ástu Guðnýju Daníelsdóttur og Halldór Guðnason og gengu frá samkomulagi sem tók í meginatriðum til eftirfarandi atriða:

**Bráðabirgðasamkomulag GF og vallareigenda:**

- Vallareigendur hafa ákveðið að selja bæði Kaffi-Sel ehf. sem á 60% eignarhlut í Selsvelli og tengdum eignum, sem og persónulegan eignarhlut sinn sem er 40% í vellinum. Vilja vallareigendur gefa GF eða aðilum á vegum GF (hér eftir nefndir kaupendur) möguleika á að kaupa völlinn áður en leitað verður kaupenda utan GF. GF kanni möguleikann á að kaupa golfvöllinn, þ.e. landið og tengdar eignir fyrir alls 150 millljónir króna og hafi til þess tíma til ársloka 2021.

- Innifalið í kaupunum: Félagið Kaffi-Sel ehf. með öllum réttindum og skyldum, félagið afhendist skuldlaust á kaupdegi (peningalegar eignir jafnt og skuldir), sem og persónulegur eignarhlutur vallareigenda.

- Nánar tilgreindar eignir: Selsvöllur, þ.e. land undir golfvöll með öllum tilheyrandi gæðum; ræktun, skurðir, vökvunarkerfi, rafkerfi, skógur skv. gildandi skipulagi. Tilgreind svæði utan skipulags; teigar 13. brautar sunnan við Litlu Laxá og svæði norð-austan við æfingasvæði þar sem efnislager er. Seljendur lýstu vilja til að láta það land fylgja með í kaupum og beita sér fyrir að leigusamningur um land undir 13. teiga yrði framlengdur.

- Allar vélar, tæki, áhöld og búnaður tengdur rekstri vallarins og á golfvellinum, eins og framræsingarkerfi. Einnig allur efnis- og vörulager tengdur golfvellinum.

- Þrjár fasteignir; núverandi golfskáli, núverandi vélageymsla ásamt áföstum gámi og núverandi bílageymsla/kaffiaðstaða. Tilgreint er að allar eignir séu gamlar og þarfnist talsverðs viðhalds.

- Veitingastofa og veitingarekstur; vélar, tæki, áhöld og búnaður í eldhúsi og matsal, veitingaleyfi fyrir 150 manns í sal og 50 á útipalli, uppskirftir, kassakerfi, bókhaldskerfi, viðskiptasambönd, vefsíða, kynningarefni og hvers konar leyfi og heimildir tengdar þessum rekstri.

- Land sem afmarkast af núverandi vegi í suðri, 5. braut, 9 braut og hosteli niður að 10. teigi og samþykkt skipulag og grunnteikningar að þessu svæði skilgreint sem hótel/veitingarekstur á gildandi skipulagi fyrir allt að 80 manns. Íbúðarhús norðan við 10 teig fylgir ekki í kaupunum, en seljendur lýsa sig reiðubúna að leigja húsnæðið til GF á hliðstæðum kjörum og verið hefur.

Með þetta samkomulag í höndum var haft samband við nokkra aðila til þess að undirbúa kynningarfund fyrir félagsmenn GF. Þeir sem komu mest að þessu starfi voru auk formanns; Stefán Franklín, Jónas Ragnarsson, Sigurjón Harðarson, Ottó Leifsson, Jón B Stefánsson og Guðmundur Konráðsson. Voru helstu verkefni eftirfarandi:

- Greina rekstur GF og Kaffi-Sels ehf. sem verið hafði aðal rekstraraðili vallarins og veitingastarfseminnar, til þess að sjá hvað til þyrfti til þess að reksturinn yrði sjálfbær til framtíðar, hver mannaflaþörf yrði o.s.frv.

- Yfirfara eignir til þess að meta rekstrarhæfi og viðhaldsþörf á næstu árum

- Huga að skipulagi kaupanna og fjármögnunarmöguleikum til þess að geta ráðið við kaupin án þess að setja forsvarsmenn rekstrarins í óásættanlega áhættu.

- Undirbúa fundinn, finna húsnæði, finna fólk til þess að taka sæti í framkvæmdanefnd að fundi loknum, auglýsa og kynna fundinn, útbúa glærur og framsetningu.

Vann hópurinn hörðum höndum að undirbúningi næstu vikur og um miðjan nóvember var eftirfarandi bréf sent út til allra félagsmanna í GF:

> Ágætu golfélagar
>
> Ástæðan fyrir þessu bréfi til ykkar er sú að eigendur Selsvallar, Unnsteinn og Halldóra, tilkynntu í september sl. að þau hefðu ákveðið að hætta rekstri vallarins og veitingasölunnar og vildu selja hvort tveggja. Fyrir okkur í GF er það mikið hagsmunamál að völlurinn verði í okkar eigu eða undir okkar stjórn, þannig að við getum bæði tryggt að að ekki verði þrengt að vellinum eða honum breytt án okkar aðkomu eða samþykkis. Tel ég þetta mikilvægt bæði upp á fasteignaverð á svæðinu og ekki síður þau lífsgæði sem góður golfvöllur og veitingaaðstaða hefur í för með sér.
>
> Eftir viðræður við eigendur Selsvallar komumst við að samkomulagi um að GF eða aðilar á vegum GF hefðu forkaupsrétt að landi, fasteignum, tækjum og aðstöðu fyrir tiltekna fjárhæð til ársloka 2021. Höfum við rýnt í rekstrartölur og átt óformlegar viðræður við aðila sem kynnu að hafa áhuga á að koma að hótel- og veitingarekstri og vera í samvinnu við GF um rekstur vallarins. Sýnist okkur að áhugavert geti verið að freista þess að kaupa völlinn og réttindi honum tengd. Til þess að það geti gerst þurfum við að safna hlutafé meðal félagsmanna til að tryggja réttindi okkar. Markmið okkar er að endurgreiða hlutafé með eðlilegri ávöxtun eins fljótt og auðið er og helst að koma eignarhaldi vallarins yfir á Gofklúbb Flúða í áföngum.
>
> Til þess að fara nákvæmlega yfir stöðu mála höfum við ákveðið að boða til kynningarfundar þriðjudaginn 23. nóv. nk. kl. 17 í Skeifunni 10, 1 hæð, Reykjavík. Í ljósi faraldursins erum við að kanna möguleika á því að streyma fundinum og látum vita í síðasta lagi mánudaginn 22. nóv. hvort af streymi verður eða ekki. Ef undirtektir eru góðar á fundinum, höfum við í huga að tilnefna undirbúningsnefnd til að vinna málið hratt áfram og boða svo í framhaldinu til formlegs stofnfundar þar sem félagsmenn geta skráð sig fyrir hlutafé.

## Kynningarfundur og undirbúningsnefnd

Mikill áhugi reyndist vera og kom fjöldi klúbbfélaga á fundinn og var mikill hugur í fólki. Rekstraryfirlit árin 2019, 2020 og 9 mánuðir 2021 var kynnt, eftir að tölum frá GF og Kaffi-Sel ehf. hafði verið skeitt saman. Kom þar fram að gera mætti ráð fyrir að tekjur **golfvallar** yrðu í besta falli 38 mkr. og gjöld án fyrninga og vaxta 25 mkr. og tekjur af **veitingasölu** yrðu í besta falli 58 mkr og gjöld án fyrninga og vaxta 53 mkr. Sem sagt, gera mætti ráð fyrir heildarframlegð upp á 18 mkr. á ári til að standa undir öllum fjárfestingum (endurbætur á vellinum, fjárfesting í vélum og tækjum og öllu sem tengdist veitingasölunni) auk vaxta. Bara vextirnir af kaupverðinu færu langt með að éta þetta allt upp, þannig að finna þyrfti fjármögnunarleiðir án kostnaðar, ætti dæmið að ganga upp. Við forsvarmenn GF höfðum ekkert komið nálægt rekstri golfvallarins eða golfskálans, því þetta hafði verið á höndum vallareigenda. Starfsemi GF hafði beinst að innheimtu félagsgjalda sem gengu að mestu leyti áfram til vallareigenda, tekjuöflun með sölu auglýsinga, fjárfestingu og smávægilegum rekstri klúbbsins. Allar rekstrartölur vallar og veitingarekstrar tóku mið af næstu árum á undan (þegar búið var að undanskilja þá þætti sem ekki stóð til að kaupa af vallareigendum) þar sem ítrasta aðhalds hafði verið gætt, t.d. var áætlað að rekstur vallarins (áburður, fræ, olíur, viðhald, tryggingar ofl.) næmi alls 5,3 mkr. og laun vallarstarfsmanna 17,3 mkr. Ekki auðveldaði það heldur áætlanir til framtíðar að þetta var í miðju covid faraldursins.

Á fundinum var stofnuð undirbúningsnefnd með það að markmiði að finna raunhæfar leiðir til að kaupa Selsvöll og kynna niðurstöður sínar fyrir félagsmönnum. Á fundinum var tilgreint að helstu störf nefndarinnar yrðu:

- Er ásættanlegt að ráðast í fjárfestinguna?

- Hvernig er rétt að haga hlutafjársöfnun?

- Hvernig er rétt að haga samningum um hotel? Fram hafði komið í kynningu að söluverð á hótelleyfum og aðstöðu gæti numið á bilinu 50-100 mkr., en ef það gengi ekki mætti selja 8-10 bústaðalóðir á svæðinu sem gæti gefið ca. 50 mkr.

- Þó stefnt sé að því að endurgreiða hlutafé til baka að 10 árum liðnum, er ekkert visst í þeim efnum.

- Huga þarf að rekstri vallarins; mönnun, endurnýjun og viðhaldi véla og tækja

- Huga þarf að framkvæmdastjórn; fyrirspurnir og skráning á völl, utanumhald um félagaskrá, utanumhald með keppnum, eftirlit með vellinum, markaðssetning, eftirlit með rekstri, bókhald, launamál, starfsmannaaðstaða

Eftir óformleg samtöl í framhaldi af fundinum sendi formaður út eftirfarandi tölvupóst til manna í undirbúningsnefnd 24. nóvember, sem lýsir nokkuð vel hvernig var unnið:

> Komið þið sælir, þakka ykkur fyrir góðan fund og ykkar framlag
>
> Við þurfum að vinna hratt og legg ég til að við hittumst nk. mánudag kl. 17 í Skeifunni 15, 2. hæð (sami staður og síðast). Á fundinum legg ég til að við sameinumst um þau atriði sem þarf að vinna að, bæði að því er varðar stofnun félagsins og söfnun hlutafjár, en ekki síður að velta fyrir okkur framtíðarrrekstri og verkefnum. Bið ég ykkur að hugsa með mér yfir helgina hvernig þessu verður best fyrir komið. Til að leggja eitthvað í púkkið nefni ég eftirfarandi:
>
> **1 Tengt stofnun félagsins:**
>
> 1)  Fara betur yfir rekstur liðinn ára og fá staðfestingu á þeim bráðabirgðatölum sem liggja fyrir, þ.e. gera “due diligence” á Kaffi-Seli ehf.
>
> 2)  Fara kerfisbundið yfir allar eignaheimildir, að land sé rétt tilgreint, að engar hömlur eða kvaðir liggi á eignum. Skilgreina hvort unnt sé að fara fram á viðbótarspildur.
>
> 3)  Fara kerfisbundið yfir öll leyfi og ganga úr skugga um til hve langs tíma þau gilda.
>
> 4)  Huga að skipulagningu félagsins, hvers konar félagsform, tenging félagsins sem safnar hlutafé og Kaffi-Sels annars vegar og GF hins vegar. Fara þarf yfir alla samninga sem eru í gildi milli félaganna. Þurfa að vera mismunandi hlutaflokkar, hvernig er auðveldast að endurgreiða hlutafé, er betra að vera með hluthafalán, hvaða skilmálar þurfa að vera?
>
> 5)  Fara að skrifa drög að samþykktum fyrir félagið, skilgreina tilgang félagsins, hvernig aðkvæði skuli skiptast, hvort setja eigi ákvæði um hámarkseign hvers og eins, hvernig fara skuli með fjármuni ef félagið verður lagt niður.
>
> **2 Tengt söfnun hlutafjár:**
>
> 1)  Kortleggja líklega aðila sem vilja vera með, kortleggja og fá forsvarsmenn á sumarbústaðasvæðum til að hafa sambandi við alla á sínu svæði. Tilgreina þarf einn með heildarsýn yfir þessu.
>
> 2)  Hvað á hver hlutur/fjárhæð (hluthafalán) að vera. Lágmark, hámark?
>
> 3)  Skal stefna að því að jafna hluti með mismunandi endurgreiðslu eða hafa annan hátt
>
> 4)  Hvaða reglur skulu gilda um arð, vexti af lánum etc.
>
> 5)  Ræða við sveitarfélagið
>
> **3 Tengt framtíðarrekstri:**
>
> 1)   Hvernig er ástand fasteigna, hvað þarf að gera og áætlaður kostnaður
>
> 2)  Hvernig er ástand vela og tækja, viðhald, endurbætur og endurnýjun
>
> 3)  Hvað er mest aðkallandi með völlinn
>
> 4)  Hvernig er best að snúa sér í útleigu veitingareksturs, endurgjald fyrir aðstöðu, samningar tengdir veitingum vegna hópa, skráining í mót, innheimtu vallargjalda
>
> 5)  Hver er mannaflaþörf vegna reksturs vallarins, hvaða samsetning væri best, hvaða einstaklingar eru á svæðinu, viðgerðarmál, etc.
>
> 6)  Hvernig er best að snúa sér í leit að hótelfjárfestum; í gegn um banka/fjárfestingarfélög, aðrar leiðir.

Eins og sjá má af þessu var að ýmsu að hyggja. Nefndin tók strax til starfa og var aðdáunarvert að sjá áhuga, frumkvæði og áræði einstakra aðila við að finna lausnir og úrræði til að af þessu gæti orðið. Til viðbótar við þá sem áður er getið bættust í hópinn Benedikt Hauksson, Eggert Á Sverrisson, Vala Valtýsdóttir, Gísli Óskarsson, Hafdís Ævarsdóttir, Einar Einarsson, Rolf Hansson, Sævar Gestur Jónsson, Pétur Oddsson, Kjartan Birgisson og Jón Björn Sigtryggsson. Fá félagar í GF seint fullþakkað þessum einstaklingum fyrir þeirra framlag.

Undirbúningsnefndin skipti með sér verkum, einbeitti sér einkum að útreikningum og yfirferð á framtíðarrekstrargrundvelli klúbbsins annars vegar og að aðferðum og möguleikum á sækja fjármagn til félaga hins vegar. Við vorum ekkert að láta það þvælast fyrir okkur hvernig við ætluðum að reka völlinn og veitingasöluna og hverja við ætluðum að fá til þess að vera þar í forsvari, hvernig við ætluðum að hýsa starfsfólk og hverjir ættu að gegna stjórnunarstöðum. Við gerðum okkar áætlanir miðað við að þetta myndi einfaldlega takast og að við myndum annast eins mikið og mögulegt væri í sjálfboðavinnu. Með þessum forsendum settum við saman rekstraráætlun til nokkurra ára, sem gekk upp miðað við hóflegar fjárfestingar og lágmarks fjármmagnskostnað fyrstu árin, samanber það sem áður hefur komið fram.

Hópurinn sem vann að fjármögnun kaupanna vann frábært starf og smám saman mótuðust og skýrðust hugmyndir sem og aðferðafræðin. Gæta þurfti þess að aðgreina eins og kostur var áhættu tengda kaupunum frá golfklúbbnum, létta eins og kostur var á fjármagnskostnaði og afborgunum fyrstu árin eftir kaup, útbúa valkosti þannig og að þeir sem leggja vildu klúbbnum til frekari fjármuni fengju eðlilegt viðbótarálag fyrir.

Reiknaðist okkur til að afla þyrfti um 130 mkr. frá félagsmönnum með þessum hætti, því fjármögnun frá bankakerfi væri út úr myndinni miðað við fjáhagsgetu klúbbsins. Það sem upp á vantaði taldi formaður að unnt væri að leysa með ýmsum aðferðum, bæði ætti GF ákveðna fjárhæð inni hjá vallareigendum sem var afrakstur samkomulags sem gert var á árinu 2015 og fjallað var um fyrr í þessari samantekt auk þess sem skattalegir vinklar gætu nýst golfklúbbnum.

Var nú hafist handa við að útbúa öll skjöl til að gera þetta mögulegt. Finna þurfti nákvæman texta til að hluthafar gætu skráð sig fyrir hlutafé og lánum, útbúa þurfti mismunandi skuldaskjöl, stofna sérstakt félag sem fékk nafnið Golf-Sel ehf. til að annast fjáröflunina, ákveða stjórnskipulag og stjórn þess, skrá félagið hjá fyrirtækjaskrá og skattinum og gera samninga milli félagsins og GF með tilheyrandi tryggingum og fjárhagsákvæðum (covenants). Einn afraksturinn af þessari vinnu var eftirfarandi skjal, sem sent var félagsmönnun til kynningar:

> Hluthafasamkomulag Golf-Sel ehf.
>
> Tilgangur félagsins er að afla fjármuna til þess að veita lán til Golfklúbbs Flúða svo hann geti fest kaup á Selsvelli og tengdum eignum og stuðlað að því að golfklúbbur og golfvöllur sé til staðar á Flúðum Hrunamannahreppi. Öllum hagnaði félagsins skal ráðstafað til almenningsheilla, samkvæmt 4. tl. 4. greinar laga nr. 90/2003.
>
> Til þess afla fjár til kaupanna eru annars vegar gefin út hlutabréf og hins vegar hluthafalán frá hluthöfum. Arður er ekki greiddur til hluthafa.
>
> Hluthafar: 3. grein samþykkta Golf-Sels ehf. hljóðar svo;
>
> > „Hlutafé félagsins má vera að hámarki kr. 1.500.000 -einmilljónogfimmhundruðþúsundkrónur - eða sem nemur 300 hlutum á kr. 5.000 og að lágmarki kr. 500.000 – fimmhundruðþúsundkrónur – eða sem nemur 100 hlutum á kr. 5.000. Eitt atkvæði fylgir hverjum hlut. Hver einstakur hluthafi má ekki eiga meira en 10% hlutafjár. Sú kvöð fylgir hverjum hlut í félaginu að lánuð sé tiltekin fjárhæð sem nánar er kveðið á um í hluthafasamkomulagi”.
>
> Hluthafasamkomulag þetta fjallar um lántökur frá hluthöfum og lánveitingu til Golfklúbbs Flúða.
>
> **Hluthafalán**
>
> Hlutafalán eru tvenns konar, Almenn hluthafalán og Sértæk hluthafalán.
>
> **Almenn hluthafalán**
>
> Við kaup á hverjum hlut kr. 5.000 skuldbindur hluthafi sig til þess að lána félaginu Almennt hluthafalán í formi skuldabréfs að fjárhæð kr. 495.000 þannig að heildar greiðsla til félagsins fyrir hvern hlut er kr. 500.000. Hámarks fjárhæð Almennra hluthafalána er kr. 148.500.000 (495.000 x 300.)
>
> Lánið er til 15 ára og afborgunarlaust og vaxtalaust fyrstu þrjú árin. Eftir það verði 12 jafnar árlegar afborganir og fyrsti gjalddagi er 48 mánuðum eftir útgáfudag skuldabréfs. Vextir fyrir hvert vaxtatímabil skulu taka mið af meðal innlánsvöxtum í Landsbankanum af innlánsreikningi Varðan 60 grunnþrep (nú 1,05%) á tímabilinu auk 1,0 prósentustigs álags, eða sambærilegs reiknings. Fyrsta vaxtagreiðsla er 48 mánuðum eftir útgáfudag skuldabréfs og miðast við fyrra 12 mánaða tímabil. Heimilt verði á lánstímanum að greiða lánið upp eða greiða inn á það að hluta umfram umsamdar afborganir.
>
> **Sértæk hluthafalán**
>
> Heimilt er að taka Sértæk hluthafalán hjá hluthöfum. Ekkert hámark er á lántökum hjá einstökum hluthöfum nema hvað varðar heimildir til heildarlántöku félagsins. Heildarlántaka félagsins má ekki vera hærri en kr. 150.000.000 nema með samþykki hluthafafundar í samræmi við samþykktir félagsins. Þessum lántökum fylgir enginn atkvæðaréttur á fundum félagsins.
>
> Félagið gefur út skuldabréf til 15 ára og skal ekki greiða afborgun af höfuðstól fyrstu þrjú árin. Eftir það verði 12 jafnar áralegar afborganir og fyrsti gjalddagi er 48 mánuðum eftir útgáfudag skuldabréfs. Vextir fyrir hvert vaxtatímabil skulu taka mið af meðal innlánsvöxtum í Landsbankanum af innlánsreikningi Varðan 60 grunnþrep (nú 1,05%) á tímabilinu auk 3,0 prósentustiga álags, eða sambærilegs reiknings Fyrsta vaxtagreiðsla er 12 mánuðum eftir útgáfudag skuldabréfs og miðast við fyrsta 12 mánaða tímabil frá útgáfu skuldabréfs. Heimilt verði á lánstímanum að greiða lánið upp eða greiða inn á það að hluta umfram umsamdar afborganir.
>
> **Lánveiting til Golfklúbbs Flúða**
>
> Samkvæmt tilgangi félagsins er félaginu heimilt að lána Golfklúbbi Flúða (GF) allt að kr. 150.000.000 til kaupa á golfvelli og tengdum eignum og mögulega til endurbóta á golfvelli og öðrum búnaði. Lánveiting skal vera tvíþætt, Fjárfestingarlán og Viðbótarlán.
>
> Fjárfestingarlán sem verði sama fjárhæð og samtals hlutafé og Almenn hluthafalán, hámark kr. 150.000.000. Lánið verði til 15 ára, afborgun og vextir þeir sömu og á Almennum hlutafalánum Golf-Sels ehf. GF skal veðsetja Golf-Sel ehf. allar eignir sínar (golfvöllur, fasteignir, búnaður og aðrir hagsmunir) til greiðslu lánsins á 2. veðrétti með uppfærslurétti. Veði verður ekki aflétt fyrr en fullnaðargreiðsla allra lána til Golf-Sels ehf. hefur verið innt af hendi. Þá skal í skuldabréfinu vera sú kvöð að Golf-Sel ehf. tilnefni á hverjum tíma 3 einstaklinga í 5 manna stjórn GF.
>
> Þær kvaðir skulu fylgja þessu láni að selji GF eignir s.s. land eða réttindi skal söluverðmæti þeirrar sölu nýtt fyrst til til greiðslu Viðbótarláns frá Golf-Seli ehf. og síðan inn á Fjárfestingalán þar til að það er að fullu greitt.
>
> Viðbótarlán er samsvarandi Sértækum hluthafalánum Golf-Sels ehf. Lánið verði til 15 ára og afborgun og vextir verði þeir sömu og á Sértækum hluthafalánum Golf-Sels ehf. GF skal veðsetja Golf-Sel ehf. allar eignir sínar (golfvöllur, fasteignir, búnaður og aðrir hagsmunir) til greiðslu lánsins á 1. veðrétti. Veði verður ekki aflétt fyrr en fullnaðargreiðsla Sértækra hluthafalána til Golf-Sels ehf. hefur verið innt af hendi. Þá skal í skuldabréfinu vera sú kvöð að Golf-Sel ehf. tilnefni á hverjum tíma 3 einstaklinga í 5 manna stjórn GF.
>
> Þær kvaðir skulu fylgja þessu láni að selji GF eignir s.s. land eða réttindi skal söluverðmæti þeirrar sölu nýtt til greiðslu Viðbótarláns umfram aðrar lánveitingar Golf-Sels ehf.
>
> Til staðfestingar undirrita hluthafar samning þennan.

## Stofnfundur og fjármögnun

Þegar komið var fram í desember töldu menn sig vera það langt komna að unnt væri að stíga næstu skref. Var félagið Golf-Sel ehf. formlega skráð 6. desember 2021, því valin bráðabirgðastjórn úr undirbúningshópnum og boðað til stofnfundar 16. desember 2021 í húsnæði sem formaður fékk að láni úti á Grandagarði í Reykjavík. Fundurinn var mjög fjölsóttur og var auk þess streymt til félagsmanna því covid flensan var enn í gangi.

Á fundinum voru niðurstöður undirbúningshópsins kynntar og m.a. farið yfir framangreint skjal “Hluthafasamkomulag Golf-Sel ehf.”. Var samþykkt að ganga til kaupa á Selsvelli og tengdum eignum ef tækist að afla nægs fjármagns. Stofnun Golf-Sels ehf. var samþykkt sem og fyrirkomulag fjármögnunar, auk þess sem stjórn GF var heimilað að ganga til samninga við Golf- Sel og vallareigendur á grundvelli þess sem áður hafði verið kynnt.

Á fundinum skrifuðu fjölmargir sig fyrir hlutafjárloforðum á þar til gerðum eyðublöðum sem útbúin höfðu verið og nokkrir gáfu til kynna að þeir væru reiðubúnir til að leggja aukalega fram fjármagn ef á þyrfti að halda. Í framhaldinu hélt undirbúningsnefndin áfram að hringja út til annarra félagsmanna og fleiri aðila sem voru á lista yfir hugsanlega þátttakendur og lauk þessu fyrir jól með mjög góðum árangri, þó enn vantaði nokkuð á til þess að réttlætanlegt væri að skrifa undir samkomulag við vallareigendur. Var tíminn milli jóla og nýárs nýttur til þess að hafa samband við valda aðila og fá þá til að leggja fram viðbótarfjármagn til að loka dæminu. Formaðurinn var búinn að setja það viðmið að safna þyrfti a.m.k. 120 mkr. til þess að réttlætanlegt væri að skrifa upp á skuldbindingu um kaup að fjárhæð 150 mkr. fyrir árslok 2021, en það voru þau tímamörk sem forkaupsréttur okkar tók til.

Frá fundinum 16. desember og fram yfir jólahátíðina var ýmist mikil bjartsýni um að þetta næðist, eða að svartsýnin náði yfirhöndinni. Menn unnu þó sleitulaut áfram og það var ekki fyrr en komið var fram á 27. desember að við skriðum fram úr 120 milljóna markinu og hafist var handa við að útbúa eftirfarandi samkomulag við vallareigendur, sem var svo undirritað 28. desember 2021:

> Yfirlýsing og samkomulag
>
> Við undirrituð, Halldóra Halldórsdóttir og Unnsteinn Logi Eggertsson eigendur að Kaffi-Sel ehf. kt. 470404-2720, í sameiningu nefndir vallareigendur og Golfklúbburinn Flúðir kt. 440491-2009, hér eftir nefndur GF, gera með sér eftirfarandi
>
> **Samkomulag**
>
> Í byrjun október 2021 gerðu vallareigendur og GF með sér samkomulag um að GF hefði forkaupsrétt að kaupum á Selsvelli og tengdum eignum fyrir 150 milljónir króna til ársloka 2021. GF hafði forgöngu um stofnun félags Golf-Sel ehf. til að fjármagna kaupin og leitaði félagið liðsinnis félaga í GF og annarra sem tengjast svæðinu um fjármögnun. Golf-Sel ehf. hefur nú boðið GF fjármögnun til kaupa á vellinum og í framhaldi af því lýsa aðilar samkomulags þessa yfir eftirfarandi:
>
> 1.  GF tilkynnir vallareigendum að gengið verði að framangreindum forkaupsrétti um að kaupa golfvöllinn Selsvöll, landnúmer 203094, fasteignamatsnúmer F2203164 Efra-Sel golfvöllur sem inniheldur eftirtaldar einingar: 01 Golfskáli 548,8m2, 02 Véla/verkfærageymsla 128m2, 03 Véla/verkfærageymsla 124m2 og 04 Fjós 39,8m2. Einnig landsvæðið „Syðra-Sel lóð 1“, fasteignanúmer F2347995 og landeignanúmer L221377, stærð er 5.735,7m2 og er á því svæði þar sem 12. flöt vallarins er staðsett. Einnig verði gengið að því að kaupa allar vélar, tæki, áhöld, búnað og innréttingar tengdar golfvelli og veitingarekstri og félagið Kaffi-Sel ehf. kt. 470404-2720 skuldlaust, en með öllum lausafjármunum, réttindum og skyldum sem því tengjast.
>
> 2.  Vallareigendur samþykkja að selja framangreindar eignir að uppfylltum ákvæðum samkomulags þessa.
>
> 3.  GF greiðir kr.150.000.000,- eitthundraðog fimmtíumilljónir - fyrir framangreindar eignir, með peningum og yfirtöku skulda miðað við stöðu í árslok 2021 fyrir lok mars mánaðar 2022, að eftirtöldum skilyrðum uppfylltum.
>
> - Með fyrirvara um samþykki aðalfundar GF sem haldinn verður 4. febrúar 2022, fyrir kaup- unum og fjármögnun þeirra.
>
> - Með fyrirvara um að samkomulag takist milli GF og Golf-Sels ehf. um fjármögnun.
>
> - Með fyrirvara um að endurskoðað uppgjör fyrir Kaffi-Sel ehf. miðað við árslok 2021 liggi fyrir ekki seinna en 25. janúar 2022 og að áreiðanleikakönnun GF leiði ekki í ljós óvissar kröfur eða skuldbindingar sem ágreiningur er um.
>
> - Að allar eignaheimildir, lóðamörk, skráð og óskráð réttindi samkomulags þessa liggi skriflega fyrir til yfirferðar í lok janúar 2022.
>
> - Að samningar um afnot af landi utan golfvallar (Teigar á 13. braut), forkaupsrétt að gistihúsnæði við golfskála (nefnt Hostel) og forleigurétt að íbúðarhúsnæði í eigu Helga E. Daníelssonar hafi tekist fyrir lok febrúar 2022.
>
> 4.  Fasteignirnar Efra-Sel hostel (fnr.F2241036) og Efra-Sel home (fnr. F2257149), ásamt tilheyrandi lóðum (nr. L203095 og L191686), eru undanskildar samkomulagi þessu, nema hvað varðar forkaupsrétt að Efra-Sel hostel, sbr. lið 3.
>
> Aðilar samkomulags þessa munu leitast við að finna lausn á ágreiningsefnum sem upp kunna að koma og stefna að því að ganga frá formlegum kaupsamningi fyrir 15. mars 2022. Forsvarsmenn GF annars vegar og forsvarsmenn Kaffi-Sels ehf. og aðrir vallareigendur hins vegar staðfesta samkomulag þetta með undirritun sinni í votta viðurvist.

## Frágangur kaupanna

Mikil vinna fór í hönd í upphafi árs 2022 tengd undirbúningi á kaupunum í lok mars. Haldinn var aðalfundur Golf-Sels í byrjun febrúar og félaginu kosin ný stjórn. Árni Tómasson lét af störfum sem formaður, þar sem ekki þótti við hæfi að hann sæti báðum megin borðs sem formaður GF og GS, og við tók Jón B. Stefánsson. Þá var lánveitingin til GF formlega samþykkt sem og annað sem tengdist skuldbindingum félagsins. Á aðalfundi GF sem haldinn var á sama tíma voru kaupin formlega staðfest og sambærilegar heimildir og lýst var í Golf-Seli voru fengnar og samþykktar. Hafist var handa við að innheimta hlutafjárloforð auk þess sem áfram tíndust inn viðbótarloforð. Útbúnir voru formlegir lánasamningar milli GF og Golf-Sels ehf. um almenn lán og sérstök lán, auk þess sem undirbúningur hófst fyrir veðtöku þinglýstra eigna til tryggingar lánunum. Jafnframt voru gerðir sambærilegir samningar við þá aðila sem lánuðu Golf-Seli fjármuni og greiddu inn hlutafé.

Þegar upp var staðið söfnuðust í gegn um Golf-Sel ehf. 125,6 milljónir króna, þar af 85,5 milljónir í almennum framlögum og 40,1 milljón í sérstökum framlögum og sömu fjárhæðir voru lánaðar til GF. Eitt almennt framlag bættist svo við á árinu 2023.

Alls voru þetta 165 einstaklingar sem lögðu til framlag (þar af voru 7 með tvo hluti hver). Af þessum 165 voru það svo 43 aðilar sem lögðu GF til viðbótarfjármagn til þess að unnt væri að loka dæminu. Til þess að það sé nefnt, voru oftar en ekki hjón á bak við hverja skráða fjárhæð, þannig að í raun voru talsvert fleiri einstaklingar sem stóðu að baki kaupunum en þeir 165 sem að framan eru tilgreindir. Ég tel að það sé einsdæmi í golfsögu á Íslandi að staðið hafi verið að kaupum á golfvelli og tengdum eignum með sambærilegum hætti og hér er lýst.

Á stjórnarfundi í GF 20. janúar 2022 var samþykkt að útbúa skjöld í golfskála með nöfnum allra þeirra sem tóku þátt í að kaupa Selsvöll á árinu 2022 og tryggja þar með veru golfvallar á Flúðum til framtíðar. Þeir sem gerast félagar í GF í framtíðinni og þeir sem spila völlinn gera sér þá vonandi grein fyrir hvað þetta fólk var reiðubúið að leggja á sig fyrir klúbbinn og komandi kynslóðir. Í [viðauka](../vidaukar/kaupendur.qmd) er að finna nöfn þeirra sem lögðu fram fé til kaupa á vellinum.

Áfram var unnið af kappi við undirbúning að endanlegum kaupum. Farið var í að finna leiðir til þess að kaupin gætu gengið sem best fyrir sig báðum aðilum til hagsbóta. Í því sambandi var farið í að skipta Kaffi-Seli ehf. upp og þær eignir, skuldir og starfsþættir sem ekki átti að selja yfir til GF voru yfirfærðar í nýtt félag, en allt annað skilið eftir í Kaffi-Seli. Í stað þess að kaupa einstakar eignir út úr félaginu, var þannig unnt að kaupa hlutféð í heild sinni eftir uppskiptingu og hagræðið sem af þessu skapaðist skiptist jafn á milli kaupenda og seljenda og dugði það til þess að fjármagna mismuninn á heildarverði og því sem tekist hafði að safna, alls um 25 milljónir króna. Þar af voru kröfur sem safnast höfðu upp í eigu GF á grundvelli samnings frá árinu 2015 samtals að fjárhæð um 17 milljónir króna. Ennfremur var farið í nákvæma áreiðanleikakönnun á Kaffi-Seli ehf. og rekstur félagsins á fyrstu þremur mánuðum ársins nákvæmlega aðskilinn, þannig að sá hluti starfseminnar sem ekki var keyptur var greindur frá, sem og rekstur tengdur golfi og veitingarekstri fram til 31. mars 2022, þegar kaupin fóru fram. Sá formaður GF alfarið um alla samningagerð og útfærslu á þessum þáttum í samvinnu við Unnstein Eggertsson.

Fara þurfti í nákvæma áreiðanleikakönnun á því landi sem keypt var og bera saman við gildandi skipulag, skráningu í veðmálabækur sem og eignarheimildir. Leiddi sú vinna til þess að gera þurfti breytingar á lóðarmörkum, breyta og uppfæra eignarheimildir, gera breytingar á gildandi skipulagi ofl. Þannig var hluti af 12. flöt og 8. flöt ekki skráður sem eign golfklúbbsins, gera þurfti nokkrar breytingar á lóðarmörkum upp af 9. teig að golfskála auk nokkurra minni háttar breytinga. Ennfremur voru vallareigendur svo vinsamlegir að innfela í viðskiptunum a.m.k. tvær góðar landspildur umfram það sem upphaflega hafði verið talað um og er þar átt við svæði aftan við núverandi æfingasvæði og svæði norðan við 17 braut. Gera þurfti eigna- og skráningarbreytingar þessu tengt. Hitann og þungann af þessu starfi báru Árni formaður GF og sá hann jafnframt um alla skjalagerð, Stefán Franklín og Unnsteinn Eggertsson af hálfu vallareigenda.

Gerður var nákvæmur véla-, tækja- og áhaldalisti tengdur golf- og veitingarekstri og gengið úr skugga um að eignaheimildir fasteigna og skráning þeirra væri rétt og þær tryggðar. Jafnframt hafði hópur manna unnið að því að kanna ástand eigna og hvað gera þyrfti til þess að tryggja verðmæti þeirra. Hitinn og þunginn af þessu starfi hvildi á Guðmundi Konráðssyni, Jónasi Ragnarssyni og Sigurjóni Harðarsyni.

Síðast en ekki síst þurfti að gera margvíslega samninga til þess að endanleg kaup gætu gengið í gegn og má þar nefna lánasamninga milli GF og vallareigenda, uppgreiðslusamninga við lánastofnanir, kaup á hlutafé, kaup á mismunandi eignarhlutum vallareigenda í einstökum eignum vallarins og kaupsamninga á ýmsum eignum milli GF og Kaffi-Sels ehf. Annaðist formaður GF gerð allra þessara samninga.

Þegar öllu þessu var lokið hittust forsvarsfólk GF og vallareigendur hinn 1. apríl 2022 og skrifuðu undir alla samninga á pallinum við golfskálann í blíðskaparveðri. Var þar með lokið löngu og ströngu ferli sem lauk með því að Selsvöllur við Efra-Sel á Flúðum ásamt öllum tengdum eignum var kominn í fulla eigu GF án þess að Golfklúbburinn þyrfti að taka nein lán önnur en frá félagsmönnum. Viljum við í GF þakka vallareigendum fyrir afar góða samvinnu og samskipti í tengslum við þessi viðskipti.

Áfram var að mörgu að hyggja m.a. að þinglýsa og skrá eignaskiptin og móta starfið í breyttu umhverfi, en nánar verður gerð grein fyrir því í næsta kafla.
