# Rekstur og stjórnun

Mikill hugur var í öllum félagsmönnum í kjölfarið á kaupunum í apríl 2022 og leystist úr læðingi ótrúlegur kraftur, þó ekki hafi menn setið auðum höndum árin á undan. Hér á eftir verður fjallað um helstu verkefni sem unnið hefur verið að á þeim fjórum árum 2022-2025 sem liðin eru frá kaupunum.

## Almannaheillafélag og golfklúbbur

Við sem stóðum að kaupunum á golfklúbbnum var umhugað um að ekki yrði hróflað við starfseminni til framtíðar. Til að tryggja það sem best og ennfremur til að skapa sem mesta einingu í klúbbnum, ákváðu forsvarsmenn GF strax og kaupin voru ákveðin að sækja um að Golfklúbburinn Flúðir yrði almannaheillafélag. Almannaheillafélag og lög klúbbsins hafa það í för með sér að enginn sérstakur eigandi er að golfklúbbnum, heldur eru það félags­menn hverju sinni sem fara með eignarhald og stjórn klúbbsins. Eini tilgangur klúbbsins er að eiga og reka golfvöll og skylda starfsemi á Selsvelli við Flúðir. Ekki er heimilt að greiða arð úr klúbbnum og skal veita öllum hagnaði til áframhaldandi starfsemi. Verði Golfklúbbur­inn lagður niður skulu allar eignir hans færðar til annars almannaheillafélags á svæðinu sem hefur sambærileg markmið og klúbburinn, en annars renna eignir hans til sveitarfélag­sins. Með þessu er annars vegar búið að festa starfsemi klúbbsins í sessi um ókomna framtíð og hins vegar að tryggja að engir árekstrar verði milli eigenda og félaga í klúbbnum hverju sinni. Vona ég að þetta hafi verið heillarík ákvörðun til framtíðar litið og er enn ein rósin í hnappa­gat þeirra sem gerðu kaupin möguleg. Umsókn um almannaheillafélag hófst á árinu 2021 og var samþykkt af Félagaskrá á árinu 2022.

## Rekstur og stjórnun klúbbsins

Eftir að ljóst varð í árslok 2021 að félagsmenn í GF myndu kaupa völlinn þurfti að huga að því hvernig skipuleggja þyrfti starfið. Enginn vallarstjóri eða vallarstarfsmenn höfðu verið ráðnir og það sama gilti um veitingareksturinn. Enginn framkvæmdastjóri var í klúbbnum eða starfsmaður á skrifstofu, öll þessi störf og stjórnun hafði verið í höndum vallareigenda áður, en fjáröflun, íþrótta- og félagsstarf auk mikils sjálfboðaliðastarfs á velli var í höndum GF.

### Ráðning veitingafólks og rekstur veitingastofu

Í ársbyrjun 2022 vorum við kynnt fyrir veitingafólki Söndru Gísladóttur og Baldri Jónassyni sem tengdist fólki úr undirbúnings­hópnum sem vann að kaupum á Selsvelli. Leist okkur vel á hugmyndir þeirra um rekstur veitingastofu í golfskálanum og voru samningar undirritaðir í mars 2022. Eftir á að hyggja vorum við að læra margt nýtt um rekstur sem þennan og hefðum örugglega getað staðið betur að verki gagnvart veitingafólkinu. Þau stóðu sig með sóma og höfðu mikinn metnað fyrir starfinu, en voru jafnframt að læra á starfsemina. Árið gekk að flestu leyti vel, þó að reksturinn væri ekki að skila því sem veitingamenn höfðu gert sér vonir um. Báðir aðilar gerðu sér góðar vonir um að næsta ár yrði betra, en rétt í árslok 2022 tilkynntu Baldur og Sandra okkur að þau hefðu fengið betra tilboð á höfuðborgar­svæðinu og spiluðu húsnæðisvandamál á Flúðum m.a. þar inn í.

Var aftur farið af stað að leita að nýjum rekstraraðila og gáfu tveir álitlegir aðilar sig fram. Eftir yfirferð var ákveðið að ganga til samninga við annan aðilann í apríl 2023 og fengum við góð meðmæli með honum frá aðilum sem tengdust golfklúbbnum á Selfossi. Eitthvað leist okkur ekki nægjanlega vel á upphafið á rekstrinum og þegar komið var fram yfir 20. maí var fullljóst orðið að ógerlegt væri að halda samstarfinu áfram og var samningum rift. Nú voru góð ráð dýr, en Unnsteinn og Halldóra sem rekið höfðu veitingastaðinn fram til 2022 ásamt öðrum klúbbfélögum tóku yfir reksturinn, réðu starfsfólk og skipulögðu starfsemina með miklum myndarbrag. Formaður GF og gjaldkeri Hafdís Ævarsdóttir tóku yfir fjármálastjórn og bókhald, en Unnsteinn og Halldóra sáu um innkaup og stýringu starfsmanna og gekk starfsemin ágætlega, þökk sé þeim og öðrum sem komu að málum. Hins vegar var ljóst að við svo búið mætti ekki sitja.

Reynsla okkar eftir þessi tvö ár var margþætt. Við gerðum okkur ljóst að ekki færi vel á því að hafa eignarhald á 60% af vellinum og veitingareksturinn undir nafni Kaffi-Sels ehf. Var því ákveðið að skipta félaginu upp miðað við ársbyrjun 2024 og færa allt eignarhald yfir í GF eignarhaldsfélag ehf. en skilja veitingaleyfi og rekstur veitingahúss eftir í Kaffi-Seli ehf. Jafnframt var ákveðið að gera kaupsamning við veitingamann hverju sinni, þannig að hann eignaðist Kaffi-Sel ehf. og gæti notað það til reksturs, en GF ætti kauprétt á hlutafé og þar með félaginu til baka, kysi hann ekki að halda áfram rekstri. Með þessum hætti var komist hjá því að endurnýja öll leyfi í hvert sinn sem nýr rekstraraðili kom að rekstrinum, með tilheyrandi kostnaði og vinnu, en kauprétturinn gerði GF kleift að hafa ávallt tök á rekstrar­leyfum og félaginu, en ekki skyldu til að taka félagið yfir ef óuppgerðar skuldir væru þar til staðar af hálfu rekstraraðila. Öll uppgjörsvinna, skiptingarferli, samningagerð og uppgjör við rekstraraðila árin 2022-2025 voru unnin af formanni GF.

Haustið 2023 var gengið til samninga við veitingamann Sæmund Kristjánsson og var við samningagerðina tekið tillit til þeirrar reynslu sem við höfðum aflað okkar, bæði var endurgjald fyrir aðstöðu lækkað og dregið verulega úr skyldu starfsfólks til að annast afgreiðslu fyrir golfvöllinn. Gekk rekstur veitingastarfseminnar sumarið 2024 mjög vel, en húsnæðismál fyrir rekstraraðila og starfsfólk var sífellt vandamál. Í ársbyrjun 2025 tilkynnti Sæmundur okkur að hann hefði fengið mjög gott starfstilboð í Reykjavík og óskaði eftir að verða leystur undan samningi.

Var farið að leita að nýjum veitingamanni með aðstoð félagsmanna og var gengið frá samningi við Guðmund Rúnar Lúðvíksson í febrúar 2025. Gekk reksturinn að flestu leyti vel árið 2025, en sem fyrr voru húsnæðis- og starfsmanna­mál krefjandi. Guðmundur ætlar að halda áfram starfsemi á árinu 2026 og þegar þetta er ritað hefur ný stjórn ákveðið að koma fyrir starfsmannaaðstöðu á staðnum, þannig að útlitið fyrir árið 2026 er gott.

### Ráðning vallarstjóra og vallarstarfsmanna

Í ársbyrjun 2022 var hafist handa við að finna vallarstjóra. Haft var samband við nokkra aðila sem sinnt höfðu starfi vallarstjóra hjá öðrum klúbbum og voru settar auglýsingar inn í fagtímarit vallarstarfsmanna. Nokkrir sýndu starfinu áhuga og hittu formaður GF og Guðmundur Konráðsson formaður vallarnefndar a.m.k. þrjá þeirra. Ekki báru þær viðræður árangur og voru húsnæðismál og viðvera á staðnum aðal þröskuldurinn. Vorum við orðnir nokkuð áhyggjufullir, því stutt var í að vorverkin hæfust. Seint í janúar bárust okkur þær upplýsingar að Daníel Halldórsson Apeland, sonur Halldórs og Ástu, væri á ákveðnum tímamótum og gæti hugsað sér að taka að sér starf vallarstjóra. Þó Daníel hefði ekki reynslu eða þekkingu af rekstri golfvalla, var hann uppalinn á svæðinu, hafði unnið með föður sínum við gerð og rekstur vallarins á árum áður og hafði ágæta þekkingu og reynslu af rekstri hvers konar véla. Síðast en ekki síst var hann búsettur á svæðinu með fjölskyldu. Ákváðum við því að slá til, ráða Daníel sem vallarstjóra frá 1. mars 2022 og kosta hann til námskeiðs í rekstri og umhirðu golfvalla í Noregi um vorið. Er skemmst frá því að segja að Daníel fann til nokkra vallarstarfsmenn og bjargaði það rekstri vallarins á árinu 2022. Hefur hann vaxið jafnt og þétt í starfi frá fyrsta degi og reynst GF afar vel. Jafnframt hefur eigin­kona hans, Gunn Apeland, komið meira og meira inn í myndina og gegnir nú, árið 2025, stöðu aðstoðarvallarstjóra. Annar starfsmaður sem reynst hefur okkur vel öll árin er Martiell xx

### Rekstur klúbbsins að öðru leyti, framkvæmdastjórn

Önnur störf en áður er talið fólust í að sjá um útleigu golfbíla og rekstur þeirra, rástíma­skráningu og afgreiðslu því tengda í golfskála, eftirlit með ræsingu, umsjón félagatals og samskipti við félaga, hugbúnaðarumsjón með skráningarkerfum, samningagerð við vinavelli, golffélög og hópa, fjármálaumsjón, starfsmannaumsjón, bókhald, íþrótta- og félagsstarf, samskipti við GSÍ, sveitarfélagið og aðra hagaðila, svo það helsta sé talið. Fyrir utan að ráða tvo sumarstarfsmenn sem skiptust á að vera í afgreiðslu auk starfsfólks veitingastofu og stýra umferð um völlinn, voru öll framangreind störf unnin meira og minna í sjálfboðavinnu fyrstu þrjú árin. Mótanefndin sá um framkvæmd allra móta, fjáröflunar­nefndin um stærstan hluta fjáröflunar, vallarnefndin um sjálfboðaliðastörf á golfvelli og stýringu framkvæmda ásamt vallarstjóra, húsanefndin sá um allt viðhald og nýfram­kvæmdir bygginga, en allt annað hvíldi á stjórn klúbbsins, einkum þeim Árna formanni og Hafdísi gjaldkera auk Einars Einarssonar, sem reyndist mikil hjálparhella í öllum hugbún­aðar­­málum og rekstri á tölvukerfum, að ónefndum ýmsum öðrum störfum. Þá var Unnsteinn Eggertsson okkur alltaf innan handar um ýmis rekstrarmál.

Haustið 2023 var Björn Hermannsson ráðinn í hlutastarf sem framkvæmdastjóri og ári seinna tók Unnsteinn Eggertsson við stöðu framkvæmdastjóra, en hann var öllum hnútum kunnugur og létti þá verulega á sjálfboðaliðum í tengslum við reksturinn á klúbbnum.

## Samningar og samstarf

### Samningar og samskipti við Golfklúbb Ásatúns

Samkomulag um samstarf GF og Golfklúbbs Ásatúns með aðild eigenda Selsvallar var upphaflega undirritað þann 26. nóvember 2016. Með samkomulaginu varð Selsvöllur heimavöllur GÁS og félagar í GÁS með full réttindi urðu jafnframt aðal- eða aukafélagar í GF. Félagsmenn GÁS með takmörkuð réttindi, svokallaðir fjaraðilar, nutu sambærilegra réttinda á Selsvelli og þeir höfðu á Ásatúnsvelli. Fyrir þessi réttindi greiddi hver fjaraðili árlega kr. 2.000 til Selsvallar og kr. 700 til GF, en fjaraðilar í GÁS á árinu 2016 voru alls tæplega 250. Samningur þessi var endurnýjaður í ársbyrjun 2021 og fjárhæðir uppfærðar.

Til þess að gera Selsvöll sem bestan úr garði lagði GÁS til framlag á árinu 2017 að fjárhæð 1,5 mkr. til vélakaupa og giltu sambærilegar reglur um þá fjárhæð og um framlag GF til vélakaupa á Selsvelli.

Í febrúar 2017 var undirritað samkomulag um kaup GF og vallareigenda að öllum vélum og tækjum Ásatúnsvallar og er gerð nánari grein fyrir því í kaflanum um fjárfestingar. Forsvarsmenn Ásatúnsklúbbsins, Sigurjón Harðarson, Árni Sófusson og Eiríkur Stefánsson ásamt eiginkonunum Valgerði Jönu og Eddunum tveim, gerðust mjög ötul í sjálfboðaliða­starfi GF. Sáu þau m.a. lengi um 16. brautina og glæddu tréstyttur, sem Halldór vallarstjóri hafði skorið út af miklum hagleik, nýju lífi með skemmtilegri málningu og sérsaumuðum treflum. Höfðu gárungarnir á orði að þar væri stjórn GF saman komin. Margt fleira er hægt að tína til og má visa til vallarnefndarinnar í því sambandi, en Sigurjón gegndi þar formennsku um tíma, studdi klúbbinn sem bakhjarl og umsjónarmaður golfmóts um verslunarmannahelgi auk þess sem þau gengu öll í margvísleg önnur sjálfboðaliðastörf.

Þær fjárhæðir sem runnið hafa til GF frá Ásatúnsklúbbnum frá því að þessi samningur var undirritaður nema alls um 4,4 mkr, þar af 3,5 mkr. frá 2022-2024. Þessu til viðbótar hefur Ásatúnsklúbburinn lagt til 2,6 milljónir króna til vélakaupa, vélageymslugáms og til vallarframkvæmda.

### Aðrir samningar og siðareglur

**Samstarfssamningur við Hrunamannahrepp** var gerður á árinu 2016, sem kvað á um árlega þóknun til GF kr. 120.000 (hækkun úr 65.000) gegn því að GF sæi um námskeið fyrir börn og unglinga auk nokkurra annarra ákvæða. Fjárhæðir samningsins voru endurnýjaður árið 2020, en árið 2023 var gerður nýr heildarsamningur. Með nýjasta samningnum var framlag hreppsins aukið í kr. 400.000 og fjárhæðin verðbætt, ákvæði komu inn um margvíslegar skyldur GF, þátttöku hreppsins í mótahaldi tengdu GSÍ og ennfremur var gerður viðamikill samningur um ýmis verk sem GF tæki að sér fyrir hreppinn. Þannig tókst að nýta betur mannskap og tæki klúbbsins, en á móti þurfti hreppurinn ekki að hafa áhyggjur af slætti og umhirðu íþróttavalla.

**Samningur um leigu á landi undir teiga á 13. braut** var gerður við Svein H Sveinsson eiganda Hrafnkelsstaða í febrúar 2022 um leigu á 460m2 svæði á bökkum Litlu-Laxár. Gildir samningurinn til 5 ára í senn og endurnýjast þannig sé honum ekki sagt upp.

**Siðareglur.** Á aðalfundi 2021 voru samþykktar siðareglur fyrir GF. Megininntak siðareglanna er að áreitni, einelti eða ofbeldi af hvaða toga sem er lýðst ekki hjá GF. Aðilar sem telja á sér brotið geta tilkynnt mál beint til samskiptaráðgjafa íþrótta- og æskulýðsstarfs á vegum ÍSÍ ([*https://samskiptaráðgjafi.is/tilkynningarform*](https://samskiptaráðgjafi.is/tilkynningarform)), eða til stjórnar GF sem kemur málinu í réttan farveg.

## Árferði

Árferði hefur mikil áhrif á starfsemi golfklúbbsins og er því áhugavert að eiga yfirlit um hvernig áraði, hvernig völlurinn kom undan vetri og hvaða áhrif þetta hafði. Lýsing á árferði samkvæmt árlegum skýrslum 2015-2025 má sjá í [viðauka](../vidaukar/arferdi.qmd).

## Ársreikningar og talnaupplýsingar

Ársreikningar klúbbsins segja sögu hans í talnaformi. Veruleg breyting verður á allri starfsemi klúbbsins árið 2022, þegar rekstur vallarins, eignarhald og veitingarekstur færist frá stofnendum yfir til GF. Ennfremur er áhugavert að eiga upplýsingar um fjárfestingar á hverju ári, fjölda félags­manna, breytingu á umferð um völlinn (taka verður tölum með fyrirvara framan af og frekar að marka breytingu milli ára) þátttöku í golfmótum, klúbb-meistara, o.fl. Upplýsingar um allt þetta er að finna í [viðauka](../vidaukar/arsreikningar.qmd).

## Hótelmál og nýtt skipulag

Kaup á Selsvelli á árinu 2022 voru möguleg með lánum frá félagsmönnum, en þeir hafa þó verið ótrúlega gjalfmildir og margir hverjir gefið klúbbnum lán sín eftir. Það breytir þó ekki því að enn er nokkuð há skuld við flagsmenn eftir og hátt vaxtastig hefur heldur ekki auðveldað málin. Fyrir liggur að endurnýja þarf vélageymslu klúbbsins og bílageymslu innan ekki margra ára, auk þess sem endurnýja þarf þak á golfskála.

Þegar kaupin voru kynnt, kom fram að stjórn klúbbsins sæi þá möguleika helsta til fjár­mögn­unar á endurgreiðslu skulda og aðkallandi fjárfestinga að selja rétt til hótelbyggingar á golfsvæðinu. Skipuð var nefnd til að gera tillögur að hótelbyggingu og breytingu á skipulagi til þess að það gæti orðið áhugaverður fjárfestingarkostur. Hefur nefndin unnið á þriðja ár undir forystu formanns GF og Valdimars Harðarsonar arkitekts að því gera breytingar á skipulagi og var nýtt aðal- og deiliskipulag fyrir byggingu allt að 85 herbergja hótels samþykkt á miðju ári 2025. Samhliða var samþykkt að heimila byggingu nýrrar véla- og bílageymslu auk starfsmannaaðstöðu á svæði austan við núverandi æfingasvæði, með góðri tengingu við golfvöllinn og hótelsvæðið.

Nefndin hefur hafið leit að fjárfestum og skilgreint helstu markmið í því sambandi, en sú leit hefur enn ekki leitt til niðurstöðu þegar þetta er ritað í upphafi árs 2026.

## Að lokum

Hér að framan hefur verið getið þess helsta í starfsemi Golfklúbbsins Flúðir á árunum 2015 til 2025. Gríðarlegar breytingar hafa átt sér stað á þessu tímabili og klúbburinn sem og völlurinn og starfsemin öll tekið miklum stakkaskiptum. Þetta hefði ekki verið gerlegt nema með mikilli samstöðu og ótúlegri fórnfýsi fjölmargra félagsmanna. Fyrir þetta vil ég þakka af heilum hug og leyfa mér að vona að framtíðin færi okkur fjölmargar ánægjustundir á þessum sælureit sem Selsvöllur er.
