---
pagetitle: "Saga Selsvallar | Yfirlit yfir helstu sjálfboðaliða"
---

# Yfirlit yfir helstu sjálfboðaliða

Hér vil ég nefna nokkra af hörðustu sjálfboðaliðunum í verklegum framkvæmdum:

Guðmundur Konráðsson, Jónas Ragnarsson, Sigurjón Harðarson, Sævar Stefánsson og Lárus Óskarsson

Aðrir sem alltaf hafa verið liðtækir í ýmis verkleg störf eru

Kjartan Birgisson, Einar Einarsson, Unnsteinn Eggertsson, Albert Einarsson, Jón Snorrason, Sveinn Sæland, Eygló Geirdal, Elín Bragadóttir, Árni Sófusson, Jón Snorrason, Hannes Ragnarsson, Guðlaugur Guðlaugsson, Kristinn Björn Einarsson, Rolf Hansson, Benedikt Hauksson, Eiríkur Stefánsson, Eddurnar og Jana, Jón Björn Sigtryggsson Gunnar Einarsson, Sigríður Dísa Gunnarsdóttir, Vilhelmína Þorvarðardóttir, Stefán Franklín, Birgir Hólm, Georg Hanna, Margrét Skúladóttir, Þóra Biering, Gauti Indriðason, Edda xxx

Þeir sem hafa verið hvað virkastir í félags- og íþóttastörfum

Helgi Guðmundsson, Anna Sigurðardóttir, Sveinn Karlsson, Ágúst Victorsson, Einar Einarsson, Hafdís Ævarsdóttir, Herdís Sveinsdóttir, Edda Svavarsdóttir, Katrín Ólöf Ástvaldsdóttir, Eggert Á Sverrisson,
